<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BinhLuanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('binh_luans')->delete();
        $now = Carbon::now();

        DB::table('binh_luans')->insert([
            [
                'id'               => 1,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 1,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Phở rất ngon, sốt vừa vặn',
                'so_luot_thich'    => 5,
                'trang_thai'       => 0,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'id'               => 2,
                'id_nguoi_dung'    => 7,
                'id_doi_tuong'     => 4,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Cơm tấm sườn ngon lắm, sẽ quay lại',
                'so_luot_thich'    => 3,
                'trang_thai'       => 0,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'id'               => 3,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 1,
                'id_binh_luan_cha' => 1,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Mình cũng nghĩ vậy!',
                'so_luot_thich'    => 2,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addMinutes(30),
                'updated_at'       => $now->copy()->addMinutes(30),
            ],
            [
                'id'               => 4,
                'id_nguoi_dung'    => 8,
                'id_doi_tuong'     => 5,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Mực nướng chưa tươi lắm',
                'so_luot_thich'    => 1,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHour(),
                'updated_at'       => $now->copy()->addHour(),
            ],
            [
                'id'               => 5,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 1,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 1,
                'noi_dung'         => 'Nhà hàng quá tốt, phục vụ nhanh gọn',
                'so_luot_thich'    => 8,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(2),
                'updated_at'       => $now->copy()->addHours(2),
            ],
            [
                'id'               => 6,
                'id_nguoi_dung'    => 7,
                'id_doi_tuong'     => 2,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 1,
                'noi_dung'         => 'Cơm tấm thơm cơm lắm, quay lại chắc',
                'so_luot_thich'    => 6,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(3),
                'updated_at'       => $now->copy()->addHours(3),
            ],
            [
                'id'               => 7,
                'id_nguoi_dung'    => 8,
                'id_doi_tuong'     => 2,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Bánh mì tươi ngon, giá bình dân',
                'so_luot_thich'    => 7,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(4),
                'updated_at'       => $now->copy()->addHours(4),
            ],
            [
                'id'               => 8,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 3,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 2,
                'noi_dung'         => 'Giao hàng mau lắm',
                'so_luot_thich'    => 4,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(5),
                'updated_at'       => $now->copy()->addHours(5),
            ],
            [
                'id'               => 9,
                'id_nguoi_dung'    => 7,
                'id_doi_tuong'     => 3,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 2,
                'noi_dung'         => 'Hàng đến bị mẩn, không hài lòng',
                'so_luot_thich'    => 0,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(6),
                'updated_at'       => $now->copy()->addHours(6),
            ],
            [
                'id'               => 10,
                'id_nguoi_dung'    => 8,
                'id_doi_tuong'     => 6,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Mực rất tươi, tươi lắm luôn',
                'so_luot_thich'    => 10,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(7),
                'updated_at'       => $now->copy()->addHours(7),
            ],
            [
                'id'               => 11,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 2,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Bún bò rất nóng và cay',
                'so_luot_thich'    => 5,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(8),
                'updated_at'       => $now->copy()->addHours(8),
            ],
            [
                'id'               => 12,
                'id_nguoi_dung'    => 7,
                'id_doi_tuong'     => 4,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 1,
                'noi_dung'         => 'Phục vụ tệ, chờ lâu quá',
                'so_luot_thich'    => 1,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(9),
                'updated_at'       => $now->copy()->addHours(9),
            ],
            [
                'id'               => 13,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 5,
                'id_binh_luan_cha' => 4,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Mình cũng vậy, tốt lắm',
                'so_luot_thich'    => 1,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(10),
                'updated_at'       => $now->copy()->addHours(10),
            ],
            [
                'id'               => 14,
                'id_nguoi_dung'    => 8,
                'id_doi_tuong'     => 1,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Phở gà có vị hơi nhạt',
                'so_luot_thich'    => 2,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(11),
                'updated_at'       => $now->copy()->addHours(11),
            ],
            [
                'id'               => 15,
                'id_nguoi_dung'    => 7,
                'id_doi_tuong'     => 1,
                'id_binh_luan_cha' => 14,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Có thêm gia vị lên sẽ ngon hơn',
                'so_luot_thich'    => 1,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(12),
                'updated_at'       => $now->copy()->addHours(12),
            ],
            [
                'id'               => 16,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 3,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Bánh mì cũng không tồi',
                'so_luot_thich'    => 3,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(13),
                'updated_at'       => $now->copy()->addHours(13),
            ],
            [
                'id'               => 17,
                'id_nguoi_dung'    => 8,
                'id_doi_tuong'     => 4,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 0,
                'noi_dung'         => 'Cơm tấm giá cả hợp lý lắm',
                'so_luot_thich'    => 4,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(14),
                'updated_at'       => $now->copy()->addHours(14),
            ],
            [
                'id'               => 18,
                'id_nguoi_dung'    => 7,
                'id_doi_tuong'     => 6,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 1,
                'noi_dung'         => 'Nhà hàng trang trí đẹp lắm',
                'so_luot_thich'    => 6,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(15),
                'updated_at'       => $now->copy()->addHours(15),
            ],
            [
                'id'               => 19,
                'id_nguoi_dung'    => 6,
                'id_doi_tuong'     => 4,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 2,
                'noi_dung'         => 'Shipper rất lịch sự',
                'so_luot_thich'    => 5,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(16),
                'updated_at'       => $now->copy()->addHours(16),
            ],
            [
                'id'               => 20,
                'id_nguoi_dung'    => 8,
                'id_doi_tuong'     => 5,
                'id_binh_luan_cha' => 0,
                'loai_doi_tuong'   => 1,
                'noi_dung'         => 'Quán này là yêu thích của mình',
                'so_luot_thich'    => 9,
                'trang_thai'       => 0,
                'created_at'       => $now->copy()->addHours(17),
                'updated_at'       => $now->copy()->addHours(17),
            ],
        ]);
    }
}
