<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonHangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('don_hangs')->delete();
        $now = Carbon::now();

        DB::table('don_hangs')->insert([
            [
                'id'                     => 1,
                'id_khach_hang'          => 1,
                'id_nha_hang'            => 1,
                'id_shipper'             => 1,
                'id_dia_chi'             => 1,
                'id_khu_vuc_giao_hang'   => 1,
                'id_coupon'              => null,
                'trang_thai'             => 3,
                'tong_tien_hang'         => 100000,
                'phi_giao_hang'          => 15000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 115000,
                'ghi_chu'                => 'Giao lúc trưa',
                'thoi_gian_du_kien_giao' => $now->copy()->addHours(1),
                'thoi_gian_dat'          => $now,
                'thoi_gian_xac_nhan'     => $now->copy()->addMinutes(5),
                'thoi_gian_giao_hang'    => $now->copy()->addHours(1),
                'phuong_thuc_thanh_toan' => 0,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 2,
                'id_khach_hang'          => 2,
                'id_nha_hang'            => 2,
                'id_shipper'             => 2,
                'id_dia_chi'             => 3,
                'id_khu_vuc_giao_hang'   => 3,
                'id_coupon'              => null,
                'trang_thai'             => 1,
                'tong_tien_hang'         => 80000,
                'phi_giao_hang'          => 12000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 92000,
                'ghi_chu'                => null,
                'thoi_gian_du_kien_giao' => $now->copy()->addHours(2),
                'thoi_gian_dat'          => $now,
                'thoi_gian_xac_nhan'     => $now->copy()->addMinutes(10),
                'thoi_gian_giao_hang'    => null,
                'phuong_thuc_thanh_toan' => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 3,
                'id_khach_hang'          => 1,
                'id_nha_hang'            => 3,
                'id_shipper'             => null,
                'id_dia_chi'             => 2,
                'id_khu_vuc_giao_hang'   => 4,
                'id_coupon'              => null,
                'trang_thai'             => 0,
                'tong_tien_hang'         => 60000,
                'phi_giao_hang'          => 10000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 70000,
                'ghi_chu'                => 'Đơn hàng mới',
                'thoi_gian_du_kien_giao' => $now->copy()->addHours(3),
                'thoi_gian_dat'          => $now,
                'thoi_gian_xac_nhan'     => null,
                'thoi_gian_giao_hang'    => null,
                'phuong_thuc_thanh_toan' => 0,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 4,
                'id_khach_hang'          => 3,
                'id_nha_hang'            => 1,
                'id_shipper'             => 1,
                'id_dia_chi'             => 1,
                'id_khu_vuc_giao_hang'   => 1,
                'id_coupon'              => null,
                'trang_thai'             => 3,
                'tong_tien_hang'         => 110000,
                'phi_giao_hang'          => 15000,
                'tien_giam_gia'          => 10000,
                'tong_thanh_toan'        => 115000,
                'ghi_chu'                => 'Nhanh quá',
                'thoi_gian_du_kien_giao' => $now->copy()->subDays(2)->addHours(1),
                'thoi_gian_dat'          => $now->copy()->subDays(2),
                'thoi_gian_xac_nhan'     => $now->copy()->subDays(2)->addMinutes(3),
                'thoi_gian_giao_hang'    => $now->copy()->subDays(2)->addHours(1),
                'phuong_thuc_thanh_toan' => 0,
                'created_at'             => $now->copy()->subDays(2),
                'updated_at'             => $now->copy()->subDays(2),
            ],
            [
                'id'                     => 5,
                'id_khach_hang'          => 1,
                'id_nha_hang'            => 4,
                'id_shipper'             => 2,
                'id_dia_chi'             => 1,
                'id_khu_vuc_giao_hang'   => 1,
                'id_coupon'              => null,
                'trang_thai'             => 3,
                'tong_tien_hang'         => 150000,
                'phi_giao_hang'          => 15000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 165000,
                'ghi_chu'                => 'Giao hàng nhanh',
                'thoi_gian_du_kien_giao' => $now->copy()->subDays(1)->addHours(1),
                'thoi_gian_dat'          => $now->copy()->subDays(1),
                'thoi_gian_xac_nhan'     => $now->copy()->subDays(1)->addMinutes(2),
                'thoi_gian_giao_hang'    => $now->copy()->subDays(1)->addHours(1),
                'phuong_thuc_thanh_toan' => 0,
                'created_at'             => $now->copy()->subDays(1),
                'updated_at'             => $now->copy()->subDays(1),
            ],
            [
                'id'                     => 6,
                'id_khach_hang'          => 2,
                'id_nha_hang'            => 1,
                'id_shipper'             => 1,
                'id_dia_chi'             => 3,
                'id_khu_vuc_giao_hang'   => 2,
                'id_coupon'              => null,
                'trang_thai'             => 2,
                'tong_tien_hang'         => 95000,
                'phi_giao_hang'          => 18000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 113000,
                'ghi_chu'                => 'Đang giao',
                'thoi_gian_du_kien_giao' => $now->copy()->addMinutes(45),
                'thoi_gian_dat'          => $now->copy()->subMinutes(15),
                'thoi_gian_xac_nhan'     => $now->copy()->subMinutes(10),
                'thoi_gian_giao_hang'    => null,
                'phuong_thuc_thanh_toan' => 1,
                'created_at'             => $now->copy()->subMinutes(15),
                'updated_at'             => $now->copy()->subMinutes(10),
            ],
            [
                'id'                     => 7,
                'id_khach_hang'          => 3,
                'id_nha_hang'            => 2,
                'id_shipper'             => 2,
                'id_dia_chi'             => 2,
                'id_khu_vuc_giao_hang'   => 3,
                'id_coupon'              => null,
                'trang_thai'             => 1,
                'tong_tien_hang'         => 85000,
                'phi_giao_hang'          => 12000,
                'tien_giam_gia'          => 5000,
                'tong_thanh_toan'        => 92000,
                'ghi_chu'                => 'Xác nhận rồi',
                'thoi_gian_du_kien_giao' => $now->copy()->addMinutes(30),
                'thoi_gian_dat'          => $now->copy()->subMinutes(5),
                'thoi_gian_xac_nhan'     => $now->copy()->addSeconds(1),
                'thoi_gian_giao_hang'    => null,
                'phuong_thuc_thanh_toan' => 0,
                'created_at'             => $now->copy()->subMinutes(5),
                'updated_at'             => $now,
            ],
            [
                'id'                     => 8,
                'id_khach_hang'          => 1,
                'id_nha_hang'            => 3,
                'id_shipper'             => 1,
                'id_dia_chi'             => 2,
                'id_khu_vuc_giao_hang'   => 4,
                'id_coupon'              => null,
                'trang_thai'             => 3,
                'tong_tien_hang'         => 70000,
                'phi_giao_hang'          => 10000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 80000,
                'ghi_chu'                => 'Hàng ngon',
                'thoi_gian_du_kien_giao' => $now->copy()->subDays(3)->addHours(1),
                'thoi_gian_dat'          => $now->copy()->subDays(3),
                'thoi_gian_xac_nhan'     => $now->copy()->subDays(3)->addMinutes(4),
                'thoi_gian_giao_hang'    => $now->copy()->subDays(3)->addHours(1),
                'phuong_thuc_thanh_toan' => 0,
                'created_at'             => $now->copy()->subDays(3),
                'updated_at'             => $now->copy()->subDays(3),
            ],
            [
                'id'                     => 9,
                'id_khach_hang'          => 2,
                'id_nha_hang'            => 4,
                'id_shipper'             => null,
                'id_dia_chi'             => 3,
                'id_khu_vuc_giao_hang'   => 1,
                'id_coupon'              => null,
                'trang_thai'             => 0,
                'tong_tien_hang'         => 200000,
                'phi_giao_hang'          => 15000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 215000,
                'ghi_chu'                => 'Đơn hàng mới',
                'thoi_gian_du_kien_giao' => $now->copy()->addHours(2),
                'thoi_gian_dat'          => $now,
                'thoi_gian_xac_nhan'     => null,
                'thoi_gian_giao_hang'    => null,
                'phuong_thuc_thanh_toan' => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 10,
                'id_khach_hang'          => 3,
                'id_nha_hang'            => 1,
                'id_shipper'             => 2,
                'id_dia_chi'             => 1,
                'id_khu_vuc_giao_hang'   => 2,
                'id_coupon'              => null,
                'trang_thai'             => 3,
                'tong_tien_hang'         => 120000,
                'phi_giao_hang'          => 18000,
                'tien_giam_gia'          => 0,
                'tong_thanh_toan'        => 138000,
                'ghi_chu'                => 'Xong rồi',
                'thoi_gian_du_kien_giao' => $now->copy()->subDays(5)->addHours(1),
                'thoi_gian_dat'          => $now->copy()->subDays(5),
                'thoi_gian_xac_nhan'     => $now->copy()->subDays(5)->addMinutes(3),
                'thoi_gian_giao_hang'    => $now->copy()->subDays(5)->addHours(1),
                'phuong_thuc_thanh_toan' => 0,
                'created_at'             => $now->copy()->subDays(5),
                'updated_at'             => $now->copy()->subDays(5),
            ],
        ]);
    }
}
