<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonAnSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('mon_ans')->delete();
        $now = Carbon::now();

        DB::table('mon_ans')->insert([
            [
                'id'                     => 1,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Bò',
                'mo_ta'                  => 'Phở bò truyền thống Hà Nội',
                'hinh_anh'               => null,
                'gia_ban'                => 50000,
                'gia_goc'                => 45000,
                'thoi_gian_chuan_bi_phut' => 10,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 2,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Gà',
                'mo_ta'                  => 'Phở gà thơm ngon',
                'hinh_anh'               => null,
                'gia_ban'                => 45000,
                'gia_goc'                => 40000,
                'thoi_gian_chuan_bi_phut' => 10,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 3,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 2,
                'ten_mon_an'             => 'Bún Bò',
                'mo_ta'                  => 'Bún bò Huế nóng',
                'hinh_anh'               => null,
                'gia_ban'                => 55000,
                'gia_goc'                => 50000,
                'thoi_gian_chuan_bi_phut' => 15,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 4,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Sườn',
                'mo_ta'                  => 'Cơm tấm sườn nướng',
                'hinh_anh'               => null,
                'gia_ban'                => 40000,
                'gia_goc'                => 35000,
                'thoi_gian_chuan_bi_phut' => 12,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 5,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Thịt',
                'mo_ta'                  => 'Bánh mì pa tê thịt',
                'hinh_anh'               => null,
                'gia_ban'                => 20000,
                'gia_goc'                => 15000,
                'thoi_gian_chuan_bi_phut' => 5,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 6,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Mực Nướng',
                'mo_ta'                  => 'Mực tươi nướng than',
                'hinh_anh'               => null,
                'gia_ban'                => 150000,
                'gia_goc'                => 130000,
                'thoi_gian_chuan_bi_phut' => 25,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 7,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Tái',
                'mo_ta'                  => 'Phở bò tái nạm',
                'hinh_anh'               => null,
                'gia_ban'                => 55000,
                'gia_goc'                => 50000,
                'thoi_gian_chuan_bi_phut' => 12,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 8,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Cá Kho',
                'mo_ta'                  => 'Cơm tấm cá kho tộ',
                'hinh_anh'               => null,
                'gia_ban'                => 45000,
                'gia_goc'                => 40000,
                'thoi_gian_chuan_bi_phut' => 15,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 9,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Pâtê',
                'mo_ta'                  => 'Bánh mì pâtê chân không',
                'hinh_anh'               => null,
                'gia_ban'                => 22000,
                'gia_goc'                => 18000,
                'thoi_gian_chuan_bi_phut' => 5,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 10,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Tom Hùm Nướng',
                'mo_ta'                  => 'Tôm hùm tươi nướng mỡ hành',
                'hinh_anh'               => null,
                'gia_ban'                => 250000,
                'gia_goc'                => 220000,
                'thoi_gian_chuan_bi_phut' => 30,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 11,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 2,
                'ten_mon_an'             => 'Bún Chả',
                'mo_ta'                  => 'Bún chả Hà Nội',
                'hinh_anh'               => null,
                'gia_ban'                => 40000,
                'gia_goc'                => 35000,
                'thoi_gian_chuan_bi_phut' => 12,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 12,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Trứng',
                'mo_ta'                  => 'Cơm tấm chiên trứng',
                'hinh_anh'               => null,
                'gia_ban'                => 35000,
                'gia_goc'                => 30000,
                'thoi_gian_chuan_bi_phut' => 8,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 13,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Gà',
                'mo_ta'                  => 'Bánh mì đùi gà xào',
                'hinh_anh'               => null,
                'gia_ban'                => 25000,
                'gia_goc'                => 20000,
                'thoi_gian_chuan_bi_phut' => 6,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 14,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Cua Hoàng Đế Nướng',
                'mo_ta'                  => 'Cua hoàng đế nướng mỡ hành',
                'hinh_anh'               => null,
                'gia_ban'                => 300000,
                'gia_goc'                => 270000,
                'thoi_gian_chuan_bi_phut' => 35,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 15,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Xương',
                'mo_ta'                  => 'Phở xương bò nấu lâu',
                'hinh_anh'               => null,
                'gia_ban'                => 60000,
                'gia_goc'                => 55000,
                'thoi_gian_chuan_bi_phut' => 15,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 16,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Gà Hainanese',
                'mo_ta'                  => 'Cơm gà Hainanese chiên',
                'hinh_anh'               => null,
                'gia_ban'                => 50000,
                'gia_goc'                => 45000,
                'thoi_gian_chuan_bi_phut' => 18,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 17,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Xá Xíu',
                'mo_ta'                  => 'Bánh mì xá xíu mềm',
                'hinh_anh'               => null,
                'gia_ban'                => 23000,
                'gia_goc'                => 19000,
                'thoi_gian_chuan_bi_phut' => 5,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 18,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Tôm Tươi Nướng',
                'mo_ta'                  => 'Tôm tươi nướng thơm lừng',
                'hinh_anh'               => null,
                'gia_ban'                => 180000,
                'gia_goc'                => 160000,
                'thoi_gian_chuan_bi_phut' => 25,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 19,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 2,
                'ten_mon_an'             => 'Bún Thang',
                'mo_ta'                  => 'Bún thang Hà Nội',
                'hinh_anh'               => null,
                'gia_ban'                => 38000,
                'gia_goc'                => 33000,
                'thoi_gian_chuan_bi_phut' => 11,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 20,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Chả Lụa',
                'mo_ta'                  => 'Cơm tấm chả lụa nấu',
                'hinh_anh'               => null,
                'gia_ban'                => 38000,
                'gia_goc'                => 33000,
                'thoi_gian_chuan_bi_phut' => 10,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
        ]);
    }
}
