<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NguoiDungSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nguoi_dungs')->delete();
        $now = Carbon::now();

        DB::table('nguoi_dungs')->insert([
            [
                'id'            => 1,
                'email'         => 'admin@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0901234567',
                'ho_ten'        => 'Admin Hệ Thống',
                'anh_dai_dien'  => null,
                'vai_tro'       => 2,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 2,
                'email'         => 'restaurant1@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0912111111',
                'ho_ten'        => 'Quản Lý Phở Hà Nội',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 3,
                'email'         => 'restaurant2@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0912222222',
                'ho_ten'        => 'Quản Lý Cơm Tấm',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 4,
                'email'         => 'restaurant3@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0912333333',
                'ho_ten'        => 'Quản Lý Bánh Mì',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 5,
                'email'         => 'restaurant4@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0912444444',
                'ho_ten'        => 'Quản Lý Seafood',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 6,
                'email'         => 'customer1@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0913111111',
                'ho_ten'        => 'Nguyễn Văn A',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 7,
                'email'         => 'customer2@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0913222222',
                'ho_ten'        => 'Trần Thị B',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 8,
                'email'         => 'customer3@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0913333333',
                'ho_ten'        => 'Lê Văn C',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 9,
                'email'         => 'shipper1@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0914111111',
                'ho_ten'        => 'Phạm Quốc D',
                'anh_dai_dien'  => null,
                'vai_tro'       => 1,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 10,
                'email'         => 'shipper2@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0914222222',
                'ho_ten'        => 'Hoàng Văn E',
                'anh_dai_dien'  => null,
                'vai_tro'       => 1,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 11,
                'email'         => 'customer4@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0913444444',
                'ho_ten'        => 'Phan Thị D',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 12,
                'email'         => 'customer5@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0913555555',
                'ho_ten'        => 'Võ Văn E',
                'anh_dai_dien'  => null,
                'vai_tro'       => 0,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 13,
                'email'         => 'shipper3@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0914333333',
                'ho_ten'        => 'Ngô Mạnh F',
                'anh_dai_dien'  => null,
                'vai_tro'       => 1,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'id'            => 14,
                'email'         => 'shipper4@example.com',
                'password'      => bcrypt('password'),
                'so_dien_thoai' => '0914444444',
                'ho_ten'        => 'Bùi Văn G',
                'anh_dai_dien'  => null,
                'vai_tro'       => 1,
                'trang_thai'    => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
        ]);
    }
}
